myblog/blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:pk>/', views.post_detail, name='detail'),
    path('category/<slug:category_slug>/', views.category_posts,
         name='category'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('pages/', include('pages.urls')),
]

myblog/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'
urlpatterns = [
    path('/about/', views.about, name='about'),
    path('/rules/', views.rules, name='rules'),
]

myblog/blogs/models.py
from django.db import models

from user.models import User


# Create your models here.
class Post(models.Model):
    title = models.CharField(
        'Зоголовок поста',
        max_length=254,
        blank=False,
        )
    text = models.TextField(
        'Текст поста',
        blank=False,
    )
    pub_date = models.DateField()
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    location = models.ForeignKey(
        'Location',
        on_delete=models.CASCADE,
        blank=True,
    )
    category = models.ForeignKey(
        'Category',
        on_delete=models.CASCADE,
        blank=False,
    )
    is_published = models.BooleanField(
        blank=False,
        default=True,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )


class Category(models.Model):
    title = models.CharField(
        max_length=256,
        blank=False
        )
    description = models.TextField(blank=False)
    slug = models.SlugField(
        unique=True,
        blank=False
    )
    is_published = models.BooleanField(default=True,)
    created_at = models.DateTimeField(auto_now_add=True)


class Location(models.Model):
    name = models.CharField(
        max_length=256,
        blank=False

    )
    is_published = models.BooleanField(
        default=True,
        blank=False
    )
    created_at = models.DateTimeField(auto_now_add=True)

myblog/pages/models.py
from django.db import models

# Create your models here.

myblog/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    sex = models.BooleanField(
        'Гендер',
        blank=True,
        null=True
        )
    nickname = models.CharField(
        'Никнейм',
        unique=True,
        max_length=20,
        blank=True,
        null=True
        )
    status = models.CharField(
        'Статус',
        max_length=30,
        blank=True,
        null=True
    )
    bio = models.TextField(
        'О себе',
        blank=True,
        null=True,
        )

myblog/blogs/views.py
from django.shortcuts import render

from .test_utils import POSTS


def index(request):
    context = {'posts': POSTS}
    return render(request, 'blogs/index.html', context)


def post_detail(request, pk):
    context = {'post': POSTS[pk]}
    return render(request, 'blogs/detail.html', context)


def category_posts(request, category_slug):
    context = {'slug': category_slug}
    return render(request, 'blogs/category.html', context)

myblog/pages/views.py
from django.shortcuts import render


# Create your views here.
def about(request):
    return render(request, 'pages/about.html')


def rules(request):
    return render(request, 'pages/rules.html')

myblog/user/views.py
from django.shortcuts import render

# Create your views here.

myblog/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href={% static "img/fav/favicon.ico" %} type="image">
    <link rel="apple-touch-icon" sizes="180x180" href={% static "img/fav/apple-touch-icon.png" %}>
    <link rel="icon" type="image/png" sizes="32x32" href={% static "img/fav/favicon-32x32.png" %}>
    <link rel="icon" type="image/png" sizes="16x16" href={% static "img/fav/favicon-16x16.png" %}>
    <link rel="stylesheet" href={% static "css/bootstrap.min.css" %}>
    <title>
        {% block title %}
        {% endblock %}
    </title>
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      {% block content %}
      {% endblock %}
    </main>
    {% include "includes/footer.html" %}
  </body>
</html>

myblog/templates/blogs/category.html
{% extends "base.html" %}
{% block title %}
  Категории
{% endblock %}
{% block content %}
      <div class="container py-5">
        <h1>Публикации в категории {{ slug }} </h1>
      </div>
{% endblock %}

myblog/templates/blogs/detail.html
{% extends "base.html" %}
{% block title %}
  Детали
{% endblock %}
{% block content %}
      <div class="container py-5">
        <article>
          <ul>
            <li>
              {{post.location}}
            </li>
            <li>
              {{post.date}}
            </li>
            <li>
              Категория: <a href="{% url 'blogs:category' post.category %}">{{post.category}}</a>
            </li>
          </ul>
          <p>
            {{post.text}}
          </p>
        </article>
      </div>
{% endblock %}

myblog/templates/blogs/index.html
{% extends "base.html" %}
{% block title %}
  Мейн Пейг
{% endblock %}
{% block content %}
      <div class="container py-5">
        <h1>Лента записей</h1>
        {% for post in posts %}
        <hr>
        <article>
          <ul>
            <li>
              Место: {{ post.location }}
            </li>
            <li>
              Дата: {{ post.date }}
            </li>
            <li>
              Категория: <a>{{ post.category }}</a>
            </li>
          </ul>

          <p>
            {{ post.text|truncatewords:10 }}
          </p>
          <a href="{% url 'blogs:detail' post.id %}">Читать полный текст</a>
        </article>
        {% endfor %}
{% endblock %}

myblog/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© Уеблог</p>
</footer>

myblog/templates/includes/header.html
<header>
    <nav class="navbar navbar-light" style="background-color: Gold">
      <div class="container">
        {% load static %}
        <a class="navbar-brand" href="{% url 'blogs:index' %}">
          <img src={% static "img/logo.png" %} width="50" height="50" class="d-inline-block align-top" alt="">
          У*блог
        </a>
        <ul class="nav  nav-pills">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blogs:index' %}">
              Лента записей
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:about' %}">
              О проекте
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:rules' %}">
              Наши правила
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

myblog/templates/pages/about.html
{% extends "base.html" %}
{% block title %}
  Правила
{% endblock %}
{% block content %}
      <div class="container py-5">
        <h1>О проекте</h1>
        <p>
          Уеблог — это дом для творческих людей. Это — сообщество людей, для которых
          нет грани вообще.
        </p>
        <p>
          Хотите кайфуйте, туда сюда. Здесь весело, можете делится музыкой или фильмами.
          А можете просто пойти на Х...
        </p>
        <p>
          Творчество, разнообразие и свобода взглядов и самовыражения —
          основные черты наших пользователей.
        </p>
      </div>
{% endblock %}

myblog/templates/pages/rules.html
{% extends "base.html" %}
{% block title %}
  Мейн Пейг
{% endblock %}
{% block content %}
      <div class="container py-5">
        <h1>Наши правила</h1>
        <p>
          <b>Cамовыражение.</b> У наших пользователей должна
          быть возможность создать что-то своё, выразить себя,
          свои мысли и чувства.
        </p>
        <p>
          <b>Многообразие.</b> Мы уважаем и приветствуем разные
          мнения и культуры. Уеблог — это место, объединяющее
          самых разных людей. Поделитесь своим уникальным взглядом на мир.
        </p>
        <p>
          <b>Творчество.</b> Не важно, в какой области вы творите,
          это может быть литература, дизайн, программирование.
          Наши инструменты помогут вам раскрыть талант максимально
          просто и комфортно.
        </p>
        <p>
          <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне.
          Делитесь своей информацией только с теми, кого выбрали.
          Как и насколько засекречивать вашу личную информацию —
          определяете вы и только вы.
        </p>
      </div>
{% endblock %}